services:
  - type: web
    name: fake-placement-detector
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd fake_placement_alert && gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
